"""Data ingestion pipeline — fetch movies from TMDB, enrich, and build index."""

import json
import logging
import os
from collections import Counter

from .models import Genre, Movie, Person
from .tmdb_client import TMDBClient

_SAMPLED_MOVIES_PATH = os.path.join(os.path.dirname(__file__), "_sampled_movies.json")

logger = logging.getLogger(__name__)


class MoviePipeline:
    """Orchestrates data ingestion from TMDB API.

    Usage:
        pipeline = MoviePipeline(api_key="...")
        movies = pipeline.run(pages=5, enrich=True)
    """

    def __init__(self, api_key: str | None = None):
        """Initialize the ingestion pipeline.

        Args:
            api_key: TMDB API key. Falls back to sample data if not set.
        """
        self.client = TMDBClient(api_key)
        self.movies: list[Movie] = []
        self.all_actors: set[str] = set()
        self.all_directors: set[str] = set()

    def run(
        self,
        pages: int = 5,
        enrich: bool = True,
        include_top_rated: bool = True,
    ) -> list[Movie]:
        """Run the full ingestion pipeline.

        Args:
            pages: Number of pages to fetch per source (popular, discover, etc.)
            enrich: Whether to fetch full credits + keywords for each movie.
            include_top_rated: Also fetch top-rated movies.
        """
        logger.info("Starting movie ingestion pipeline...")

        # Step 1 — Fetch brief movie lists
        raw: list[Movie] = []
        raw.extend(self.client.fetch_popular_movies(pages=pages))

        if include_top_rated:
            raw.extend(self.client.fetch_top_rated_movies(pages=pages))

        # Also discover across key genres to get diversity
        genre_batches = [
            [28, 12],        # Action, Adventure
            [35],            # Comedy
            [18],            # Drama
            [27, 53],        # Horror, Thriller
            [878, 14],       # Sci-Fi, Fantasy
            [10749, 35],     # Romance, Comedy
            [80, 9648],      # Crime, Mystery
            [99],            # Documentary
            [16, 10751],     # Animation, Family
        ]
        for batch in genre_batches:
            try:
                discovered = self.client.discover_movies(
                    genres=batch,
                    pages=max(1, pages // 3),
                )
                raw.extend(discovered)
            except Exception as e:
                logger.warning(f"Discover batch {batch} failed: {e}")

        # Deduplicate by tmdb_id
        seen: set[int] = set()
        unique: list[Movie] = []
        for m in raw:
            if m.tmdb_id not in seen:
                seen.add(m.tmdb_id)
                unique.append(m)
        raw = unique
        logger.info(f"Fetched {len(raw)} unique movies (brief)")

        # Step 2 — Enrich with full details
        if enrich:
            enriched: list[Movie] = []
            total = len(raw)
            for i, movie in enumerate(raw):
                try:
                    full = self.client.enrich_movie(movie)
                    enriched.append(full)

                    # Collect known people
                    for a in full.actors:
                        self.all_actors.add(a.name)
                    for d in full.directors:
                        self.all_directors.add(d.name)

                    if (i + 1) % 20 == 0:
                        logger.info(f"Enriched {i + 1}/{total} movies...")
                except Exception as e:
                    logger.warning(f"Failed to enrich movie {movie.tmdb_id} '{movie.title}': {e}")
                    enriched.append(movie)  # keep the brief version
            self.movies = enriched
        else:
            self.movies = raw

        logger.info(
            f"Ingestion complete: {len(self.movies)} movies, "
            f"{len(self.all_actors)} actors, {len(self.all_directors)} directors"
        )
        return self.movies

    def run_sample(self) -> list[Movie]:
        """Load the 1 000-movie sample dataset from a pre-built JSON file.

        This provides a fallback for demo/offline use with hand-picked and
        synthetic movies across all genres. Backdrop and poster paths for
        the 17 real movies come from TMDB's public CDN.

        The JSON is generated by ``scripts/generate_movies.py`` and shipped
        with the repository.
        """
        with open(_SAMPLED_MOVIES_PATH, "r", encoding="utf-8") as f:
            raw = json.load(f)

        movies: list[Movie] = []
        for item in raw:
            genres: list[Genre] = []
            for g in item.get("genres", []):
                try:
                    genres.append(Genre(g["value"]))
                except ValueError:
                    pass

            actors: list[Person] = []
            for a in item.get("actors", []):
                actors.append(Person(
                    tmdb_id=a["tmdb_id"],
                    name=a["name"],
                    role=a.get("role", "Actor"),
                    character=a.get("character", ""),
                    popularity=a.get("popularity", 0.0),
                    profile_path=a.get("profile_path", ""),
                ))
                self.all_actors.add(a["name"])

            directors: list[Person] = []
            for d in item.get("directors", []):
                directors.append(Person(
                    tmdb_id=d["tmdb_id"],
                    name=d["name"],
                    role=d.get("role", "Director"),
                    popularity=d.get("popularity", 0.0),
                    profile_path=d.get("profile_path", ""),
                ))
                self.all_directors.add(d["name"])

            movies.append(Movie(
                tmdb_id=item["tmdb_id"],
                title=item["title"],
                overview=item.get("overview", ""),
                release_date=item.get("release_date", ""),
                genres=genres,
                vote_average=item.get("vote_average", 0.0),
                vote_count=item.get("vote_count", 0),
                popularity=item.get("popularity", 0.0),
                poster_path=item.get("poster_path", ""),
                backdrop_path=item.get("backdrop_path", ""),
                tagline=item.get("tagline", ""),
                runtime=item.get("runtime", 0),
                budget=item.get("budget", 0),
                revenue=item.get("revenue", 0),
                actors=actors,
                directors=directors,
                keywords=item.get("keywords", []),
                language=item.get("language", "en"),
            ))

        self.movies = movies
        logger.info(f"Loaded {len(movies)} movies from sample dataset")
        return movies

